name: Doc

on:
  workflow_run:
    workflows: ["Submodule update"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy doc page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: true
      - uses: actions/setup-node@master
        with:
          node-version: '18.x'
      - name: Build
        run: bash build.sh
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: doc
